### ISSUE TITLE
Strange video issue

### ISSUE THREAD

**Issue by aiobofh** [c0pperdragon/Amiga-Digital-Video#42]
Hi there!

I have this very strange video issue. Picture looks crisp clear, but with three ribbons of weirdly (wedge-)shaped garble horizontally..

When first turned on, they move a (very) little bit vertically, but after that, they stay where they are on the photo.

Any spontaneous ideas?
![20210311_223241](https://user-images.githubusercontent.com/1361958/110858859-e2786100-82ba-11eb-9507-825941dd7e44.jpg)

B.t.w. This is running on a Rev5 A500, with kickrom-adapter and kickstart 1.3 on EPROM. Analog video output looks amazing. This board was bought from and built by a 3rd party. I soldered the headers to the pi and went through them again this morning the solder joints there look fine, added a bit of solder to a couple of them where i may have been a bit quick last night. Anyway. Same issue still. There are no other interesting wires needed for Rev5-boards that i have may have missed?

**Comment by aiobofh** [comment]
... Addition.... I tried another monitor than the TV i took the photo of above.. (That TV has been quite friendly with all other sources i've thrown at it... So this is weird.). Result on my workstation monitor: 

![20210312_080858](https://user-images.githubusercontent.com/1361958/110906360-2182d280-830c-11eb-80cd-b056a422343d.jpg)

... How come?

**Comment by IanSB** [comment]
@aiobofh 
>How come?

The first monitor probably doesn't like the non-standard timings produced by the genlock.

First thing to try is manually changing the resolution to 1920x1080 and the refresh to 50Hz. (Assuming that's a 1080p monitor)
This will produce a more standard 1080p 50Hz output but it will still be a little off frequency due to the genlock.

If that doesn't work then try switching the genlock off in the settings menu although that means the video output won't be locked to the input so you might get tears and dropped/repeated frames.

**Comment by aiobofh** [comment]
@IanSB right you are!

Strange that that otherwise friendly TV did not like it. Anyhow. End-goal was to have crisp up-scaled picture in the livingroom TV. Just tried it out there and it works fine! Thanks for the tip!

End result:

![zoom](https://user-images.githubusercontent.com/1361958/110965105-2e2b1900-8354-11eb-854c-b9e78b980239.jpg)
